site_name: My Docs
site_url: https://moita2025.github.io/
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.copy
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite 
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - macros:
      module_name: macros

nav:
  - 首页: index.md
  - 编程:
      - Code_Programming/index.md
      - 网页开发:
          - Code_Programming/Web_Development/index.md
      - Python:
          - Code_Programming/Python/index.md
          - 文件处理:
              - 遍历查询后缀名: Code_Programming/Python/File_System/FileExtTraverse.md
          - 图像处理:
              - 随机噪声位图: Code_Programming/Python/Image/RandomNoise.md
      - Markdown:
          - RMD 标头: Code_Programming/Markdown/RmdHeader.md
  - 语言:
      - Languages/index.md
      - 英语词汇:
          - Languages/English_Vocab/Words.md
          - Languages/English_Vocab/WordDetail.md
          - Languages/English_Vocab/Practice_en2zh_mcq.md
      - 托福:
          - Languages/TOEFL_iBT/index.md
          - 考试内容:  Languages/TOEFL_iBT/about.md
          - 阅读:
              - Languages/TOEFL_iBT/Reading/Intro.md
              - 题型:
                  - Languages/TOEFL_iBT/Reading/Questions/FactInfoQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/NegFactInfoQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/InferQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/RhetPurpQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/VocabQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/ReferQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/SentSimplQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/InserTextQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/PsgSummQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/FillTabQ.md
              - 方法:
                  - Languages/TOEFL_iBT/Reading/Methods/TitPredStru.md
                  - Languages/TOEFL_iBT/Reading/Methods/AdvStruPatn.md
                  - Languages/TOEFL_iBT/Reading/Methods/NotMethRefi.md
              - Languages/TOEFL_iBT/Reading/ArtiSubjClasList.md
              - Languages/TOEFL_iBT/Reading/ArticleVocab.md
              - Languages/TOEFL_iBT/Reading/Example.md
          - 听力:
              - Languages/TOEFL_iBT/Listening/Intro.md
              - Languages/TOEFL_iBT/Listening/ChairListeningMethod.md
              - Languages/TOEFL_iBT/Listening/Example.md
          - 口语:
              - Languages/TOEFL_iBT/Speaking/Intro.md
              - Languages/TOEFL_iBT/Speaking/SpeakScorCrtr.md
              - Languages/TOEFL_iBT/Speaking/GeneralTemplate.md
          - 写作:
              - Languages/TOEFL_iBT/Writing/Intro.md
  
  - 金融:
      - 汇率: Finance/Currencies.md