site_name: My Docs
site_url: https://moita2025.github.io/
theme:
  name: material
  features:
    - content.code.copy
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite 
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details

plugins:
  - search
  - macros:
      module_name: macros

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3.2.2/es5/tex-mml-chtml.js
  - assets/javascripts/back_to_top.js
  - assets/javascripts/third_party/twemoji.min.js
  - assets/javascripts/third_party/rough-notation.iife.js
  - assets/javascripts/third_party/chart.js
  - assets/javascripts/exchange_chart.js
  - assets/javascripts/third_party/fuse.js
  - assets/javascripts/word_list/word_data_search.js

extra_css:
  - assets/stylesheets/back_to_top.css
  - assets/stylesheets/controls.css
  - assets/stylesheets/compact_grid.css
  - assets/stylesheets/pagination.css
  - assets/stylesheets/word/word_letter_index_buttons.css
  - assets/stylesheets/word/word_data_search.css
  - assets/stylesheets/word/word_test_style.css

nav:
  - 首页: index.md
  - 编程:
      - Code_Programming/index.md
      - 网页开发:
          - Code_Programming/Web_Development/index.md
          - 自定义浏览器插件 DIYFilter:
              - 文件 1: Code_Programming/Web_Development/DIYFilter/s1-c1-f1-1.md
              - 文件 2: Code_Programming/Web_Development/DIYFilter/s1-c1-f1-2.md
          - Flask:
              - 文件 1: Code_Programming/Web_Development/Flask/s1-c1-f2-1.md
      - Python:
          - Code_Programming/Python/index.md
          - 文件处理:
              - 遍历查询后缀名: Code_Programming/Python/File_System/FileExtTraverse.md
          - 图像处理:
              - 随机噪声位图: Code_Programming/Python/Image/RandomNoise.md
      - Markdown:
          - RMD 标头: Code_Programming/Markdown/RmdHeader.md
  - 语言:
      - Languages/index.md
      - 英语词汇:
          - 初中词汇:
              - Languages/English_Vocab/Junior_Vocab/Words.md
          - 高中词汇:
              - Languages/English_Vocab/Senior_Vocab/Words.md
          - 四级词汇:
              - Languages/English_Vocab/Cet4_Vocab/Words.md
              - Languages/English_Vocab/Cet4_Vocab/Practice_en2zh_mcq.md
          - 六级词汇:
              - Languages/English_Vocab/Cet6_Vocab/Words.md
          - 考研词汇:
              - Languages/English_Vocab/PG_Vocab/Words.md
          - 托福词汇:
              - Languages/English_Vocab/TOEFL_Vocab/Words.md
          - SAT词汇:
              - Languages/English_Vocab/SAT_Vocab/Words.md
      - 托福:
          - Languages/TOEFL_iBT/index.md
          - 考试内容:  Languages/TOEFL_iBT/about.md
          - 阅读:
              - Languages/TOEFL_iBT/Reading/Intro.md
              - Languages/TOEFL_iBT/Reading/ArtiSubjClasList.md
              - 题型:
                  - Languages/TOEFL_iBT/Reading/Questions/SentSimplQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/NegFactInfoQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/InferQ.md
                  - Languages/TOEFL_iBT/Reading/Questions/PsgSummQ.md
  
  - 金融:
      - 汇率: Finance/Currencies.md